# Generated by Django 3.0.5 on 2020-07-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
