# Generated by Django 3.0.5 on 2020-07-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_remove_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created',
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='users_like',
        ),
    ]
