# Generated by Django 3.0.5 on 2020-07-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='images/%y/%m/%d'),
        ),
    ]
