# Generated by Django 3.0.5 on 2020-07-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20200729_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
    ]
